[package]
name = "b_shot"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15" # make sure this is the latest version
bevy_aseprite_ultra = "0.4.1"
rand = { version = "0.8.3" }
uuid = { version =  "1.16.0"  , features = ["js"] }  
[target.'cfg(target_arch = "x86_64")'.dependencies]
bevy_remote_inspector = "0.1.0"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1


[[example]]
name = "update_enemy_list"
path = "src/main_game/update_enemy_list.rs"

